### ISSUE TITLE
"Game Over" text does not disappear when hitting "Try again" button or "New Game" button

### ISSUE THREAD

**Issue by KlavierCat** [claudiopro/2048-react#2]
Browser: 
Chrome Version 45.0.2454.93 (64-bit)

Issue:
When Game Over, I expect the semi-transparent overlay with the text "Game Over" to disappear after I hit the "Try again" button or the "New Game" button, but it does not disappear. However, moving the arrow keys after hitting the "Try again" button or "New Game" button will remove the "Game Over" text together with the semi-transparent overlay.

**Comment by claudiopro** [comment]
@KlavierCat thanks for reporting, I'll get it fixed in the next round of edits!

**Comment by claudiopro** [comment]
Resolved with b30e6a7.
