### ISSUE TITLE
I have a React Native clone of it!

### ISSUE THREAD

**Issue by liuhong1happy** [claudiopro/2048-react#4]
https://github.com/ReactLover/react-native-2048

**Comment by claudiopro** [comment]
This is awesome! I had thought about it but had no time to try. Thanks for sharing :smile:

**Comment by liuhong1happy** [comment]
Oh,Sorry! It only have android...

**Comment by claudiopro** [comment]
Thanks for nudging me, but please use issues for actual software bugs of this project (I should clarify in the `CONTRIBUTING` file of this repo) :smile:
